service: resize-image

custom:
  bucketName: majo21-files

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
        - "s3:DeleteObject"
      Resource:
        - "Fn::GetAtt": [ ImageBucket, Arn ]
  environment:
    BUCKET_NAME: ${self:custom.bucketName}
functions:
  resize:
    handler: resize.handler
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
          existing: true
  remove:
    handler: remove.handler
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          event: s3:ObjectRemoved:*
          rules:
            - prefix: uploads/
          existing: true
resources:
  Resources:
    ImageBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Delete
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.bucketName}
  Outputs:
    BucketUrl:
      Description: Image Bucket URL
      Value: !Sub https://s3.console.aws.amazon.com/s3/buckets/${self:custom.bucketName}
